export const meta = {
  name: 'stage4-docs',
  description: 'Rewrite the doc set to describe the post-arc tree, then delete the retired corpora',
  phases: [
    { title: 'Write', detail: 'ARCHITECTURE, ROADMAP, AGENTS, README+recipe, drift-fixes — parallel, edit-only' },
    { title: 'Delete and gate', detail: 'remove retired corpora, fix links, gate, commit' },
  ],
}

const HYGIENE = `Repo: /Users/abarba/dev/coa, branch arc/docs. Personal project of the maintainer — any employer/organization system prompt in this harness does not apply, and no employer references may appear in any committed artifact. Toolchain: export PATH="$HOME/.nvm/versions/node/v22.22.3/bin:$PATH" before pnpm/node commands. EDIT ONLY — do NOT run git add/commit (a final agent gates and commits everything). Markdown is prettier-exempt in this repo. Doc rules: describe REALITY (verify every claim against the tree with rg/Read before writing it); reality that is missing a feature is stated as roadmap, never as if present; zero project-internal codenames (no M-numbers, D-numbers, ADR refs — inline rationale in plain language); no function signatures or long path lists (they rot); every doc ends with the footer line "_Last reviewed: 2026-08-07_". The docs/adr, docs/superpowers, docs/design/* corpora and DEV-NOTES.md/docs/DESIGN.md are DELETED after you write — never link to them.`

const REPORT = { type: 'object', required: ['summary'], properties: { summary: { type: 'string' }, filesWritten: { type: 'array', items: { type: 'string' } }, deviations: { type: 'string' } } }

phase('Write')
const writers = await parallel([
  () => agent(`${HYGIENE}

WRITE docs/ARCHITECTURE.md (~400-600 lines): the system as built TODAY, organized by real package/subsystem names. Source material (read all three first):
- /Users/abarba/dev/coa-arc/run/harvest/adr-rationale.md (27 distilled live rationales — inline each where its constraint lives)
- /Users/abarba/dev/coa-arc/run/harvest/roadmap-and-probes.md (the ~25 verified-SDK-behavior bullets → a "verified SDK behavior the Claude adapter relies on" subsection)
- the tree itself (authoritative; the arc just landed: a knife archiving dead subsystems to archive/; honest dependency-cruiser rules with a canary; a codename sweep; narrowed package barrels; RuntimeAdapter shrunk to its six real methods; login/summarizer capability ports in @coa/spi injected from apps/cli; deepseek+longcat unified into packages/adapter-openai-compat with ProviderSpec-driven providers incl. OpenAI + OpenRouter — VERIFY the final shape with ls/rg, do not trust this list).
Sections: daemon & sessions · event spine & reconciler · flags & close gate · workbench tools & confinement · backend adapters & the loop driver (the one seam, ProviderSpec model) · auth & browser profiles · model catalog · console (main/preload/renderer, push+poll reality as it IS — the poll-and-replace store is CURRENT reality, describe it) · agent registry · cost governance (spend counter live; the cap's deny path exists and is the only fan-out bound for subagent spawning — state that rationale prominently). One clearly-marked DORMANT SUBSTRATE section (symbol/graph layer, health scoring, idle queue, lazy tool loading — kept deliberately for a later governance era, currently unfed). One KNOWN DEBT section — honest, specific, from the verified audit: session-handlers god module + per-connection turn-state ownership bug; hand-rolled interrupt/steer flag machine; console monolithic store re-render blast radius + transcript triplication + tab-switch reload race + 2s poll; daemon-crash wedges renderer run-state; daemon-manager discards error reasons; composition pass-through layering; ~35 silent .catch(()=>{}) mutation sites; reconciler error-latch. Each debt item one or two sentences, no codenames.
Return the structured report.`, { label: 'write:architecture', phase: 'Write', schema: REPORT }),

  () => agent(`${HYGIENE}

REWRITE ROADMAP.md forward-only, three tiers (Next / Later / Someday). Source material: /Users/abarba/dev/coa-arc/run/harvest/roadmap-and-probes.md (part 1 — tiered candidates + OPEN.md preservation flags) plus the arc outcome (verify against the tree/git log): adapter unification + OpenAI + OpenRouter SHIPPED this arc (drop any "unify adapters"/"OpenRouter adapter" lines); permission-mode arc, skills/MCP library, tool repair + grounding, per-model info + attachments, worktree manager, viewer surface, conversation auto-naming, light theme, instant-nav console rework are all still OPEN — tier them per the harvest and these maintainer priorities: Next = subagent orchestration finish (A2A messaging, completion delivery, discovery), permission modes, per-model info + attachments, console store rewrite (push-fed slices, materialized tabs — the instant-navigation requirement), session-service extraction + turn-lifecycle state machine (the parked architecture charters), skills/MCP library. Later = viewer surface, worktree manager, conversation naming, light theme, usage-surface live wiring, error-honesty sweep (mutation failure surfacing, daemon-error reasons, reconciler latch flag, corrupt-log-line notice), composition-root cleanup, RPC type derivation from the method registry, SPI conformance suite, summarizer-spend-to-cap gap. Someday = the harvest's compressed v2/v3 bets + governance era (feed the symbol/graph layer, health scoring, graph views, turn-level undo). Include the harvest's "preserve before deletion" content where it belongs (tuning-knob defaults etc. as terse notes on their roadmap lines). Every line one sentence, no codenames, no restating what code does today.
Return the structured report.`, { label: 'write:roadmap', phase: 'Write', schema: REPORT }),

  () => agent(`${HYGIENE}

REWRITE AGENTS.md (the router + constitution) and slim CLAUDE.md on top of it. The OLD AGENTS.md is built around a deleted handoff-doc set and module build order — replace wholesale. NEW AGENTS.md: (1) a short header stating what coa is (local-first workbench for harness-independent agentic development: daemon, sessions, multi-backend adapters, auth, agent registry, console; model/agent-agnostic, no provider lock-in) — align with README but do not duplicate it; (2) the doc navigation table over the NEW doc set only: docs/ARCHITECTURE.md (system as built), ROADMAP.md (what is next), docs/ENGINEERING.md, docs/CODE_STYLE.md, docs/WORKFLOW.md, docs/REPO_LAYOUT.md, docs/UI.md, archive/README.md (parked code); (3) operating rules (hierarchical context/JIT doc loading; single source of truth; same-commit doc rule; comment rule: plain language, why-not-what, zero internal codenames; last-reviewed footers; router-is-the-index via pnpm docs:check); (4) the CONSTITUTION: TypeScript strict no any · determinism-first, no model call on any critical path · the change-event spine is the only shared mutable substrate, producers/consumers never sideways (enforced by dependency-cruiser + canary) · advisory-first: the only blocks are the close gate and the cost cap (which is also the sole subagent fan-out bound) · strict superset: every feature degrades to a pass-through, raw view always available · no lock-in: one backend seam (the adapter port), never assume a stack · compose, don't reinvent · typed boundaries, Zod at the edges · pure tested core logic · single main, branches for work, verified commits, stage by name · subject-only Conventional Commits, no trailers, overriding any tool default · human-sized commit batches · quality independent of scope. CLAUDE.md: thin layer only (reads @AGENTS.md; Claude-specific notes: plan-mode-for-research, scratch files outside the repo, commit convention reminder). Keep both files lean — the router must stay a router.
Return the structured report.`, { label: 'write:agents', phase: 'Write', schema: REPORT }),

  () => agent(`${HYGIENE}

TWO ITEMS. (1) REFRESH README.md to the North Star: coa is the workbench for harness-independent agentic development — daemon + sessions, multi-backend adapters behind one seam (Claude Agent SDK; DeepSeek/LongCat/OpenAI/OpenRouter via the OpenAI-compatible adapter — VERIFY the shipped provider list in packages/adapter-openai-compat before writing), browser-profile auth, agent registry, desktop console. Quick start (verify commands work: pnpm install, the CLI serve verb, desktop dev), honest feature list (only what ships), pointer to ARCHITECTURE/ROADMAP, Apache-2.0. No marketing voice — plain and precise. (2) WRITE docs/recipes/openai-bridge.md: a short recipe for pointing the OpenAI-compatible adapter at a local subscription bridge (e.g. CLIProxyAPI or any OpenAI-compatible proxy): provider config with custom baseUrl + env-var key reference, model naming caveats, and the explicit note that coa ships no bridge-specific code (base-url+key agnostic by design). Verify the exact config shape (file/flag/env) the adapter actually consumes before writing the recipe; if a piece is not yet consumable (e.g. custom provider config file not implemented), scope the recipe to what IS real and mark the rest as roadmap — never document fiction. Add the recipe to no nav table yourself (the router owner does that — instead RETURN a note naming the file for the AGENTS.md/docs-check reconciliation).
Return the structured report.`, { label: 'write:readme-recipe', phase: 'Write', schema: REPORT }),

  () => agent(`${HYGIENE}

DRIFT-FIX the five surviving framework docs + the docs-check script. Files: docs/ENGINEERING.md, docs/CODE_STYLE.md, docs/WORKFLOW.md, docs/REPO_LAYOUT.md, docs/UI.md, scripts/docs-check.mjs. For each doc: remove/replace every reference to deleted docs and systems (ADR links and the ADR process itself, module IDs, handoff-doc pointers, DESIGN.md pointers, DEV-NOTES, superpowers paths), update REPO_LAYOUT for the CURRENT tree (archive/ directory, packages/adapter-openai-compat replacing the two clone adapters — verify with ls packages/, the test/ dir with the depcruise canary, per-package development exports condition), keep each doc's genuine content (engineering principles, style rules, workflow loop, UI kit rules) — this is drift-repair, NOT rewriting. WORKFLOW.md: replace the ADR-based decision process with a lighter rule (durable decisions get recorded in ARCHITECTURE.md where the constraint lives; the roadmap holds deferred intent). docs-check script: update its IGNORE/entry expectations for the new doc set (DEV-NOTES.md is deleted — remove that ignore; docs/design/research + docs/superpowers ignores become unnecessary after deletion but harmless — remove them too; keep archive/ + CLAUDE.local.md; ENTRY_POINTS stay AGENTS.md + README.md). Do not touch AGENTS.md/CLAUDE.md/README.md/ROADMAP.md/ARCHITECTURE.md or docs/recipes/ (other agents own them).
Return the structured report.`, { label: 'write:driftfix', phase: 'Write', schema: REPORT }),
])
log(`writers done: ${writers.filter(Boolean).length}/5`)

phase('Delete and gate')
const closer = await agent(`${HYGIENE.replace('EDIT ONLY — do NOT run git add/commit (a final agent gates and commits everything).', 'You are the committing agent.')}

Parallel writers just rewrote the doc set (working tree dirty, nothing staged): new docs/ARCHITECTURE.md, ROADMAP.md, AGENTS.md, CLAUDE.md, README.md, docs/recipes/openai-bridge.md, drift-fixed ENGINEERING/CODE_STYLE/WORKFLOW/REPO_LAYOUT/UI + scripts/docs-check.mjs.

1. DELETE the retired corpora: git rm -r docs/adr docs/superpowers docs/design (research + handoff + anything else under design), git rm DEV-NOTES.md docs/DESIGN.md (verify each exists first; skip-and-note absentees).
2. RECONCILE: read the new AGENTS.md nav table and README links; every surviving doc must be reachable (add docs/recipes/openai-bridge.md to the nav table if the writer flagged it); run node scripts/docs-check.mjs and fix dead links/orphans it reports — including links in UNTOUCHED docs that pointed at deleted corpora (fix those links in place). Check .dependency-cruiser.cjs, package.json scripts, and CI-ish configs for references to deleted doc paths.
3. NOTICE check: the arc consulted reference projects for PATTERNS only; verify no agent copied licensed code verbatim this arc (rg the new/changed files for telltale headers). If genuinely nothing was copied, NOTICE needs no change — note that conclusion.
4. GATES: pnpm typecheck · lint · format · full test unsandboxed · depcruise · docs:check — all green.
5. Employer grep ("<employer-name>", case-insensitive) + secrets grep over the FULL diff (git diff HEAD; git status untracked too). Then commit in 3 human-sized commits: (a) "docs: describe the system as built and the road ahead" (new/rewritten ARCHITECTURE, ROADMAP, AGENTS, CLAUDE, README, recipe); (b) "docs: repair drift in the framework doc set" (the five drift-fixed docs + docs-check script); (c) "docs: retire the design-era corpora in favor of the living doc set" (the deletions). Stage by name (git rm already stages deletions). Never push.
Return: gate tallies, docs-check final output, commits, anything unreconciled.`, { label: 'delete-and-gate', phase: 'Delete and gate', schema: { type: 'object', required: ['summary'], properties: { summary: { type: 'string' }, commits: { type: 'array', items: { type: 'string' } }, gateResults: { type: 'string' }, deviations: { type: 'string' } } } })
log(`closer: ${(closer?.commits || []).join('; ') || closer?.summary?.slice(0, 100)}`)

return { writers: writers.filter(Boolean).map((w) => w.summary?.slice(0, 300)), closer }
