import type { GraphEdge, SymbolRecord } from '@coa/shared';
import type { GenerationRelation, GenerationRunner } from './ssot-constraint.js';

/**
 * L-GEN — the seam L-GEN publishes to L-GND (GEN-7), via the kernel's sanctioned
 * edge-writer path (`declareSymbols` / `assertEdge`). Two facts per declared
 * generation relation:
 *
 *  - **`declared_symbols()`** — the symbols generation *will* produce, declared
 *    under the target (`generated:true`). Because `declareSymbols` indexes into
 *    the same `name → SymbolRecord` table the existence tier reads, a symbol a
 *    spec will generate is no longer a false-miss before the target is built.
 *  - **the `generated-from` edge** — `target ⇐ source` regenerate provenance
 *    (the shared edge semantics), a declared structural fact independent of whether
 *    the output is canonicalizable.
 *
 * The symbol set comes from regenerating the target and extracting its symbols
 * (the injected {@link SymbolExtractor} composes the parser's `parse` + `extractSymbols`);
 * binary / non-canonicalizable output yields no symbols but still records
 * provenance. The `governed-by` half of the seam — `target ⇐ governing constraint`
 * — is the **unforgeable authority link**: it is emitted ONLY when a
 * registered constraint governs the relation (resolved by the injected
 * `governingConstraint`), so coa can never claim a target is governed by a check
 * that does not exist. It points at the registered constraint (not the raw source
 * spec) at file granularity, reusing the target's established node identity;
 * per-symbol refinement waits for symbols to become first-class graph nodes.
 */

/** Extract the symbols a relation's regenerated bytes define (the parser's `parse` + `extractSymbols`). */
export type SymbolExtractor = (relation: GenerationRelation, bytes: string) => SymbolRecord[];

/**
 * Resolve the registered constraint governing a relation's target, or `undefined`
 * when none is registered. The unforgeable-link guard (option b): the wiring
 * returns the constraint id ONLY if it is a registered flag producer, so a
 * `governed-by` edge can never point at a check that does not exist.
 */
export type GoverningConstraint = (relation: GenerationRelation) => string | undefined;

/** The kernel edge-writer surface the seam publishes through (the kernel satisfies it structurally). */
export interface SeamPublisher {
  declareSymbols(symbols: SymbolRecord[], from: string): void;
  assertEdge(edge: GraphEdge): void;
}

export interface GenerationSeam {
  /** The names generation will produce, so L-GND does not false-miss a not-yet-generated type. */
  readonly declaredSymbols: ReadonlySet<string>;
}

/**
 * Publish the L-GEN→L-GND seam for `relations` into the kernel, returning the union of
 * declared symbol names (`declared_symbols()`).
 */
export function publishGenerationSeam(
  relations: readonly GenerationRelation[],
  runner: GenerationRunner,
  extract: SymbolExtractor,
  publisher: SeamPublisher,
  governingConstraint?: GoverningConstraint,
): GenerationSeam {
  const declaredSymbols = new Set<string>();

  for (const relation of relations) {
    publisher.assertEdge({
      from: relation.target,
      to: relation.source,
      type: 'generated-from',
      provenance: 'declared',
    });

    const constraint = governingConstraint?.(relation);
    if (constraint !== undefined) {
      publisher.assertEdge({
        from: relation.target,
        to: constraint,
        type: 'governed-by',
        provenance: 'declared',
      });
    }

    const fresh = runner.regenerate(relation);
    if (fresh.kind !== 'text') continue;

    const symbols = extract(relation, fresh.bytes).map((symbol) => ({
      ...symbol,
      generated: true,
    }));
    if (symbols.length > 0) publisher.declareSymbols(symbols, relation.target);
    for (const symbol of symbols) declaredSymbols.add(symbol.name);
  }

  return { declaredSymbols };
}
