import type { GraphEdge, SymbolRecord } from '@coa/shared';
import type { GenerationRelation, GenerationRunner } from './ssot-constraint.js';

/**
 * M4 / L-GEN — the seam L-GEN publishes to L-GND (GEN-7), via M1's sanctioned
 * edge-writer path (`declareSymbols` / `assertEdge`). Two facts per declared
 * generation relation:
 *
 *  - **`declared_symbols()`** — the symbols generation *will* produce, declared
 *    under the target (`generated:true`). Because `declareSymbols` indexes into
 *    the same `name → SymbolRecord` table the existence tier reads, a symbol a
 *    spec will generate is no longer a false-miss before the target is built.
 *  - **the `generated-from` edge** — `target ⇐ source` regenerate provenance
 *    (SPEC §M0 edge semantics), a declared structural fact independent of whether
 *    the output is canonicalizable.
 *
 * The symbol set comes from regenerating the target and extracting its symbols
 * (the injected {@link SymbolExtractor} composes M2 `parse` + `extractSymbols`);
 * binary / non-canonicalizable output yields no symbols but still records
 * provenance. The `governed-by` half of the seam — `symbol ⇐ governing spec`,
 * consumed only by L-GND's spec tier — is deferred with that tier (its endpoint
 * semantics, source-spec vs. registered constraint, are the spec tier's to fix).
 */

/** Extract the symbols a relation's regenerated bytes define (M2 `parse` + `extractSymbols`). */
export type SymbolExtractor = (relation: GenerationRelation, bytes: string) => SymbolRecord[];

/** The M1 edge-writer surface the seam publishes through (the kernel satisfies it structurally). */
export interface SeamPublisher {
  declareSymbols(symbols: SymbolRecord[], from: string): void;
  assertEdge(edge: GraphEdge): void;
}

export interface GenerationSeam {
  /** The names generation will produce, so L-GND does not false-miss a not-yet-generated type. */
  readonly declaredSymbols: ReadonlySet<string>;
}

/**
 * Publish the L-GEN→L-GND seam for `relations` into M1, returning the union of
 * declared symbol names (`declared_symbols()`).
 */
export function publishGenerationSeam(
  relations: readonly GenerationRelation[],
  runner: GenerationRunner,
  extract: SymbolExtractor,
  publisher: SeamPublisher,
): GenerationSeam {
  const declaredSymbols = new Set<string>();

  for (const relation of relations) {
    publisher.assertEdge({
      from: relation.target,
      to: relation.source,
      type: 'generated-from',
      provenance: 'declared',
    });

    const fresh = runner.regenerate(relation);
    if (fresh.kind !== 'text') continue;

    const symbols = extract(relation, fresh.bytes).map((symbol) => ({
      ...symbol,
      generated: true,
    }));
    if (symbols.length > 0) publisher.declareSymbols(symbols, relation.target);
    for (const symbol of symbols) declaredSymbols.add(symbol.name);
  }

  return { declaredSymbols };
}
